services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yogayo_container
    image: yogayo_image
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_PROD_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_PROD_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PROD_PASSWORD}
      - your-bucket-name=${your-bucket-name}
      - yourAccessKey=${yourAccessKey}
      - yourSecretKey=${yourSecretKey}
    depends_on:
      - mysql
    command: ["java", "-jar", "/yogayo.jar"]
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PROD_PASSWORD}
      MYSQL_DATABASE: yogayo
    ports:
      - "3306:3306"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge